# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'alarm.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AlarmDialog(object):
    def setupUi(self, AlarmDialog):
        AlarmDialog.setObjectName("AlarmDialog")
        AlarmDialog.resize(420, 240)
        self.verticalLayout = QtWidgets.QVBoxLayout(AlarmDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.labelTip = QtWidgets.QLabel(AlarmDialog)
        self.labelTip.setObjectName("labelTip")
        self.verticalLayout.addWidget(self.labelTip)
        self.timeEdit = QtWidgets.QTimeEdit(AlarmDialog)
        self.timeEdit.setMinimumSize(QtCore.QSize(220, 40))
        self.timeEdit.setObjectName("timeEdit")
        self.verticalLayout.addWidget(self.timeEdit)
        self.labelSingle = QtWidgets.QLabel(AlarmDialog)
        self.labelSingle.setObjectName("labelSingle")
        self.verticalLayout.addWidget(self.labelSingle)
        self.horizontalLayoutBtn = QtWidgets.QHBoxLayout()
        self.horizontalLayoutBtn.setObjectName("horizontalLayoutBtn")
        self.btnCancel = QtWidgets.QPushButton(AlarmDialog)
        self.btnCancel.setObjectName("btnCancel")
        self.horizontalLayoutBtn.addWidget(self.btnCancel)
        self.btnOk = QtWidgets.QPushButton(AlarmDialog)
        self.btnOk.setObjectName("btnOk")
        self.horizontalLayoutBtn.addWidget(self.btnOk)
        self.verticalLayout.addLayout(self.horizontalLayoutBtn)

        self.retranslateUi(AlarmDialog)
        QtCore.QMetaObject.connectSlotsByName(AlarmDialog)

    def retranslateUi(self, AlarmDialog):
        _translate = QtCore.QCoreApplication.translate
        AlarmDialog.setWindowTitle(_translate("AlarmDialog", "设定闹钟"))
        self.labelTip.setText(_translate("AlarmDialog", "请选择闹钟时间"))
        self.labelSingle.setText(_translate("AlarmDialog", "目前本程序支持单个单次闹钟"))
        self.btnCancel.setText(_translate("AlarmDialog", "取消"))
        self.btnOk.setText(_translate("AlarmDialog", "确定"))
