# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(660, 380)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayoutDate = QtWidgets.QHBoxLayout()
        self.horizontalLayoutDate.setObjectName("horizontalLayoutDate")
        self.lcdYear = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdYear.setDigitCount(4)
        self.lcdYear.setMinimumSize(QtCore.QSize(110, 60))
        self.lcdYear.setObjectName("lcdYear")
        self.horizontalLayoutDate.addWidget(self.lcdYear)
        self.labelYear = QtWidgets.QLabel(self.centralwidget)
        self.labelYear.setObjectName("labelYear")
        self.horizontalLayoutDate.addWidget(self.labelYear)
        self.lcdMonth = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdMonth.setDigitCount(2)
        self.lcdMonth.setMinimumSize(QtCore.QSize(70, 60))
        self.lcdMonth.setObjectName("lcdMonth")
        self.horizontalLayoutDate.addWidget(self.lcdMonth)
        self.labelMonth = QtWidgets.QLabel(self.centralwidget)
        self.labelMonth.setObjectName("labelMonth")
        self.horizontalLayoutDate.addWidget(self.labelMonth)
        self.lcdDay = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdDay.setDigitCount(2)
        self.lcdDay.setMinimumSize(QtCore.QSize(70, 60))
        self.lcdDay.setObjectName("lcdDay")
        self.horizontalLayoutDate.addWidget(self.lcdDay)
        self.labelDay = QtWidgets.QLabel(self.centralwidget)
        self.labelDay.setObjectName("labelDay")
        self.horizontalLayoutDate.addWidget(self.labelDay)
        self.labelWeekText = QtWidgets.QLabel(self.centralwidget)
        self.labelWeekText.setObjectName("labelWeekText")
        self.horizontalLayoutDate.addWidget(self.labelWeekText)
        self.lcdWeek = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdWeek.setDigitCount(1)
        self.lcdWeek.setMinimumSize(QtCore.QSize(50, 60))
        self.lcdWeek.setObjectName("lcdWeek")
        self.horizontalLayoutDate.addWidget(self.lcdWeek)
        self.verticalLayout.addLayout(self.horizontalLayoutDate)
        self.lcdHMS = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdHMS.setDigitCount(8)
        self.lcdHMS.setMinimumSize(QtCore.QSize(620, 200))
        self.lcdHMS.setObjectName("lcdHMS")
        self.verticalLayout.addWidget(self.lcdHMS)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 660, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "桌面时钟"))
        self.labelYear.setText(_translate("MainWindow", "年"))
        self.labelMonth.setText(_translate("MainWindow", "月"))
        self.labelDay.setText(_translate("MainWindow", "日"))
        self.labelWeekText.setText(_translate("MainWindow", "星期"))
