# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'timer.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TimerDialog(object):
    def setupUi(self, TimerDialog):
        TimerDialog.setObjectName("TimerDialog")
        TimerDialog.resize(440, 260)
        self.verticalLayout = QtWidgets.QVBoxLayout(TimerDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lcdTimer = QtWidgets.QLCDNumber(TimerDialog)
        self.lcdTimer.setDigitCount(8)
        self.lcdTimer.setMinimumSize(QtCore.QSize(350, 80))
        self.lcdTimer.setObjectName("lcdTimer")
        self.verticalLayout.addWidget(self.lcdTimer)
        self.horizontalLayoutCheck = QtWidgets.QHBoxLayout()
        self.horizontalLayoutCheck.setObjectName("horizontalLayoutCheck")
        self.chkMs = QtWidgets.QCheckBox(TimerDialog)
        self.chkMs.setObjectName("chkMs")
        self.horizontalLayoutCheck.addWidget(self.chkMs)
        self.chkHour = QtWidgets.QCheckBox(TimerDialog)
        self.chkHour.setChecked(True)
        self.chkHour.setObjectName("chkHour")
        self.horizontalLayoutCheck.addWidget(self.chkHour)
        self.verticalLayout.addLayout(self.horizontalLayoutCheck)
        self.horizontalLayoutBtn = QtWidgets.QHBoxLayout()
        self.horizontalLayoutBtn.setObjectName("horizontalLayoutBtn")
        self.btnStartPause = QtWidgets.QPushButton(TimerDialog)
        self.btnStartPause.setObjectName("btnStartPause")
        self.horizontalLayoutBtn.addWidget(self.btnStartPause)
        self.btnReset = QtWidgets.QPushButton(TimerDialog)
        self.btnReset.setObjectName("btnReset")
        self.horizontalLayoutBtn.addWidget(self.btnReset)
        self.verticalLayout.addLayout(self.horizontalLayoutBtn)

        self.retranslateUi(TimerDialog)
        QtCore.QMetaObject.connectSlotsByName(TimerDialog)

    def retranslateUi(self, TimerDialog):
        _translate = QtCore.QCoreApplication.translate
        TimerDialog.setWindowTitle(_translate("TimerDialog", "计时器"))
        self.chkMs.setText(_translate("TimerDialog", "显示毫秒"))
        self.chkHour.setText(_translate("TimerDialog", "显示小时"))
        self.btnStartPause.setText(_translate("TimerDialog", "开始(暂停)"))
        self.btnReset.setText(_translate("TimerDialog", "重置"))
